// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn5ORd5HFb13OB0W3SoQcUDSIZz6BuXFo',
    appId: '1:469697821998:web:22268a51fdebf9b5f80ebf',
    messagingSenderId: '469697821998',
    projectId: 'fir-204-3754a',
    authDomain: 'fir-204-3754a.firebaseapp.com',
    storageBucket: 'fir-204-3754a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9C1Gwccf-Vqf__Fn5sDPnqJC-GsyZypA',
    appId: '1:469697821998:android:bf5c54bc74dd1702f80ebf',
    messagingSenderId: '469697821998',
    projectId: 'fir-204-3754a',
    storageBucket: 'fir-204-3754a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDaUcnZpKhtpsmbahOxyFaiGOsR-EcXfo',
    appId: '1:469697821998:ios:fd0e69d9dedb236af80ebf',
    messagingSenderId: '469697821998',
    projectId: 'fir-204-3754a',
    storageBucket: 'fir-204-3754a.appspot.com',
    iosBundleId: 'com.example.firebase204',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDaUcnZpKhtpsmbahOxyFaiGOsR-EcXfo',
    appId: '1:469697821998:ios:fd0e69d9dedb236af80ebf',
    messagingSenderId: '469697821998',
    projectId: 'fir-204-3754a',
    storageBucket: 'fir-204-3754a.appspot.com',
    iosBundleId: 'com.example.firebase204',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn5ORd5HFb13OB0W3SoQcUDSIZz6BuXFo',
    appId: '1:469697821998:web:71cb594760bafb5cf80ebf',
    messagingSenderId: '469697821998',
    projectId: 'fir-204-3754a',
    authDomain: 'fir-204-3754a.firebaseapp.com',
    storageBucket: 'fir-204-3754a.appspot.com',
  );
}
